import { expect, test } from "@playwright/test";

const evidence = { id: "ev_e2e", run_id: "e2e-run", module_id: "roblox-data", kind: "fact", claim: "The game had 3,821 concurrent players when observed.", source: { type: "fixture", url: "https://games.roblox.com/v1/games?universeIds=2", retrieved_at: "2026-08-29T12:00:00.000Z", cache_key: "fixture" }, observation: { value: 3821, unit: "concurrent_players", raw_ref: "raw/core.json" }, derivation: null, support_strength: "high", relationship: "supports", related_claim_ids: [], notes: "Cached test evidence", used_by: ["orchestrator", "critic", "report"] };
const run = { id: "e2e-run", input: { game_url: "8737899170", user_mode: "developer", profile_id: "demo-replay", optional_modules: ["market-intelligence", "critic"] }, state: "COLLECT_CORE", game_name: "Build A Boat Odyssey", universe_id: "2", profile_snapshot: { id: "demo-replay", version: 1, label: "Demo replay", description: "Cached fixture", enabled_modules: ["roblox-data", "market-intelligence", "critic"], enabled_tools: ["fixture"], module_versions: { "roblox-data": "1.0.0", "market-intelligence": "1.0.0", critic: "1.0.0" }, model: "fixture", limits: { max_iterations: 8, max_runtime_ms: 240000, max_external_calls: 18, max_critic_cycles: 2, max_cost_usd: 1.5 }, search: { locale: "en-US", country: "US", device: "desktop" }, fixture_mode: true }, error: null, created_at: "2026-08-29T12:00:00.000Z", updated_at: "2026-08-29T12:00:01.000Z" };
const report = { run_id: "e2e-run", game: { name: "Build A Boat Odyssey", place_id: "8737899170", universe_id: "2", creator: "Odyssey Works", observed_at: "2026-08-29T12:00:00.000Z", thumbnail_url: null }, user_mode: "developer", verdict: { breakout_potential: "HIGH", confidence: "MEDIUM", recommendation: "Watch persistence after the update window." }, initial_verdict: { breakout_potential: "HIGH", confidence: "HIGH" }, audit_cards: [{ module_id: "roblox-data", label: "Roblox data", status: "completed", summary: "3,821 playing · 93.8% likes", evidence_ids: ["ev_e2e"], warnings: [] }, { module_id: "market-intelligence", label: "Market & social", status: "completed", summary: "Creator diversity reviewed.", evidence_ids: [], warnings: [] }, { module_id: "critic", label: "Verification", status: "completed", summary: "Durability constrained confidence.", evidence_ids: ["ev_e2e"], warnings: [] }], supporting_claims: [{ id: "c1", text: "Live engagement and approval are promising.", evidence_ids: ["ev_e2e"] }], risk_claims: [{ id: "c2", text: "Persistence is not established by one snapshot.", evidence_ids: ["ev_e2e"] }], critic: { changed_assessment: true, summary: "Potential held, but confidence fell because durability is unproven.", objections: [{ id: "o1", severity: "medium", summary: "One snapshot cannot prove persistence.", affected_claim_ids: ["c1"], evidence_ids: ["ev_e2e"], resolution_request: "Reduce confidence and monitor persistence.", resolved: true }] }, next_action: "Watch persistence after the update window.", monitor: ["Concurrent-player persistence"], limitations: ["Cached fixture report"], source_failures: [], runtime_ms: 850, approximate_cost_usd: 0, evidence_ids: ["ev_e2e"], is_fixture: true };

test("home exposes the core submission flow", async ({ page }) => {
  await page.route("**/api/runs", async (route) => route.request().method() === "GET" ? route.fulfill({ json: { runs: [] } }) : route.continue());
  await page.goto("/"); await expect(page.getByRole("heading", { name: /Find the signal/ })).toBeVisible(); await expect(page.getByLabel("ROBLOX GAME URL OR PLACE ID")).toBeVisible(); await expect(page.getByRole("button", { name: /RUN THE AUDIT/ })).toBeVisible();
});

test("submits, follows visible progress, opens report and evidence", async ({ page }) => {
  let detailReads = 0;
  await page.route("**/api/runs", async (route) => route.request().method() === "POST" ? route.fulfill({ status: 201, json: { run_id: "e2e-run", state: "QUEUED" } }) : route.fulfill({ json: { runs: [] } }));
  await page.route("**/api/runs/e2e-run/evidence", async (route) => route.fulfill({ json: { evidence: [evidence] } }));
  await page.route("**/api/runs/e2e-run", async (route) => { detailReads += 1; await route.fulfill({ json: detailReads === 1 ? { run, events: [{ id: "event-1", run_id: "e2e-run", sequence: 0, state: "COLLECT_CORE", level: "info", event_type: "state.collect_core", message: "Resolving game identity and collecting current Roblox evidence", data: {}, created_at: "2026-08-29T12:00:00.000Z" }], report: null } : { run: { ...run, state: "COMPLETED" }, events: [], report } }); });
  await page.goto("/"); await page.getByLabel("ROBLOX GAME URL OR PLACE ID").fill("8737899170"); await page.getByLabel("ANALYSIS PROFILE").selectOption("demo-replay"); await page.getByRole("button", { name: /RUN THE AUDIT/ }).click();
  await expect(page).toHaveURL(/\/runs\/e2e-run/); await expect(page.getByText("LIVE INVESTIGATION")).toBeVisible(); await expect(page.getByText("Resolving game identity and collecting current Roblox evidence")).toBeVisible();
  await expect(page.getByText("BREAKOUT POTENTIAL")).toBeVisible({ timeout: 5000 }); await expect(page.getByText("HIGH", { exact: true }).first()).toBeVisible();
  await page.getByRole("button", { name: /Roblox data/ }).click(); await expect(page.getByText("EVIDENCE WORKSPACE")).toBeVisible(); await expect(page.getByText(/3,821 concurrent players/)).toBeVisible();
});
